["sql.iuzrthikrzuiuz"]
db_type = "PostgreSQL"
host = "iuztiz"
port = "izutitzu"
database = "tuiutzi"
user = "uitzi"
password = "tzuizui"
sql = "rujhgfdjhtghgj"

["gcp.trial"]
service_account_json_path = "blahblah"
project_id = "try_project"
schema = "llm"
table = "inference"
