hugging_face_token = ""
openai_token = ""
db_type = "PostgreSQL"
host = ""
port = ""
database = ""
user = ""
password = ""

[aws_secrets]
aws_access_key_id = "YOUR_ACCESS_KEY"
aws_secret_access_key = "YOUR_SECRET_KEY"
region = "YOUR_AWS_REGION"
